### ISSUE TITLE
Look at/fix %Dc_update_meta_file macro

### ISSUE THREAD

**Issue by jdev42092** [NeighborhoodInfoDC/TANF#5]
When run as part of Read_FS_2014_07 batch submit, I received the following errors: 

ERROR: A character operand was found in the %EVAL function or %IF condition where a numeric operand is required. The 
 condition was: %upcase( &ds_lib ) ~= %upcase( &ds_lib_r ) 
 ERROR: The macro DC_UPDATE_META_FILE will stop executing.

We should review and resolve this issue.

**Comment by ptatian** [comment]
The code for processing the TANF and FS data should be updated to use the %Finalize_data_set() macro (in L:\SAS\Macros), rather than calling %DC_update_meta_file() directly. This may fix this problem.
